### ISSUE TITLE
Add data layers from Control Shift

### ISSUE THREAD

**Issue by ejucovy** [350dotorg/350map.org#7]
350 has two Control Shift installations:

`https://campaigns.gofossilfree.org`
`https://campaigns.350.org`

Each one has a list of "categories":

`https://campaigns.gofossilfree.org/categories.json?callback=foo`

You can fetch all the petitions in a category:

`https://campaigns.gofossilfree.org/categories/fossil-fuel-divestment-religious-institutions.json?callback=foo`

^^ Note that this is paginated, so fetching all the data will probably need multiple requests.

I think we should treat each category as its own map layer, and perhaps include them in a similar way as the actionkit ones:

`<script src="js/script.js" data-controlshift="campaigns.gofossilfree.org:fossil-fuel-divestment-religious-institutions|campaigns.gofossilfree.org:fossil-fuel-divestment-cities-states|campaigns.350.org:climate-impacts">`

(Any less ugly way to do that?)

**Comment by chinaowl** [comment]
We will be using

`<script src="js/script.js" data-map-args="controlshift=campaigns.gofossilfree.org:fossil-fuel-divestment-religious-institutions|campaigns.gofossilfree.org:fossil-fuel-divestment-cities-states|campaigns.350.org:climate-impacts">`

**Comment by ejucovy** [comment]
PR #10
